### ISSUE TITLE
Images folder shouldn't be flattened

### ISSUE THREAD

**Issue by simple-nicholas** [ben-rogerson/agency-webpack-mix-config#5]
The images in source (src/images) are dropped into the dist folder with all sub folders flattened. This causes issues if there are images with the same file name, and is a hassle if you want to use sub folders.

Can be easily changed by replacing line 272 of webpack.mix.js with `context: "src"`.

Edit: typo and formatting

**Comment by ben-rogerson** [comment]
fixed!
