### ISSUE TITLE
Fonts not available in dev

### ISSUE THREAD

**Issue by simple-nicholas** [ben-rogerson/agency-webpack-mix-config#6]
When running the development server, fonts in the source folder aren't available to the site (ie https://localhost:8080/webpack-dev-server doesn't show them).

They get copied to the dist folder fine though.

**Comment by ben-rogerson** [comment]
When running `npm run dev` the fonts folder gets copied across and the files are available.
I suspect there was an issue with something else that prevented the initial build.
